let productos = [
    {
        class: "living",
        id: 1, 
        name: "Sofá Nordico de 3 cuerpos Tela Chenille", 
        price: 407999, 
        medidas: "Medidas: 1.8 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Capacidad para 3 personas y soporte de hasta 350 kg de peso",
        desc2: "Estructura de madera resistente y patas negras para mayor estabilidad",
        img:'../images/living/id1', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "enabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 2, 
        name: "Sillón Sofa Esquinero Tela Rustic", 
        price: 582749,  
        medidas: "Medidas: 1.8 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Capacidad para 3 personas y soporte de hasta 350 kg de peso",
        desc2: "Estructura de madera resistente y patas negras para mayor estabilidad",
        img:'../images/living/id2', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 3, 
        name: "Sillon Sofa Trento 3 Cuerpos Chenille Jumper Antidesgarro", 
        price: 347171,  
        medidas: "Medidas: 1.8 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Capacidad para 3 personas y soporte de hasta 350 kg de peso",
        desc2: "Estructura de madera resistente y patas negras para mayor estabilidad",
        img:'../images/living/id3', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "enabled",
        cantidad: 0
    },
    {
        class: "comedor",
        id: 4, 
        name: "Juego Comedor Nórdico Mesa Escandinava 120 + 4 Sillas Eames", 
        price: 275148,  
        medidas: "Medidas: 70 cm de ancho, 120 cm de largo y 75 cm de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/comedor/id4', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
    {
        class: "comedor",
        id: 5, 
        name: "Combo Escandinavo Extensible Mesa 120 A 160 + 4 Sillas Tulip", 
        price: 390199,  
        medidas: "Medidas: 70 cm de ancho, 120 cm de largo y 75 cm de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/comedor/id5', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
    {
        class: "comedor",
        id: 6, 
        name: "Banqueta Premium Alta Desayunador Taburete Silla Bar Barra", 
        price: 135999,  
        medidas: "Medidas: 70 cm de ancho, 120 cm de largo y 75 cm de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/comedor/id6', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "enabled",
        cantidad: 0
    },
    {
        class: "comedor",
        id: 7, 
        name: "Mesa Barra De Cocina Desayunador Para 4 Personas 150x60 Cm", 
        price: 270000,  
        medidas: "Medidas: 70 cm de ancho, 120 cm de largo y 75 cm de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/comedor/id7', 
        cuotas:"Hasta 18 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 8, 
        name: "Sillon Trento 1 Cuerpo Chenille Jumper", 
        price: 210393,  
        medidas: "Medidas: 1 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/living/id8', 
        cuotas:"Hasta 6 cuotas sin interés",
        stock: "enabled",
        colors: "enabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 9, 
        name: "Sillon Sofa Nevada 3 Cuerpos Premium Ergonomico Chenille", 
        price: 531198,  
        medidas: "Medidas: 1.8 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/living/id9', 
        cuotas:"Hasta 12 cuotas sin interés",
        stock: "enabled",
        colors: "enabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 10, 
        name: "Sillón Poltrona Reclinable Pana", 
        price: 220500,  
        medidas: "Medidas: 1 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/living/id10', 
        cuotas:"Hasta 6 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 11, 
        name: "Sillon Sofa 3 Cuerpos Nevada Chenille Zaffiro Negro", 
        price: 531198,  
        medidas: "Medidas: 1.8 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/living/id11', 
        cuotas:"Hasta 12 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
    {
        class: "living",
        id: 12, 
        name: "Sofá Cama Cubo Premium gris claro chenille jumper", 
        price: 408843,  
        medidas: "Medidas: 1.8 m de ancho, 0.8 m de profundidad y 0.8 m de altura",
        desc1: "Ofrece alta resistencia y durabilidad por su resistencia al calor y por no absorber la humedad.",
        desc2: "No cuenta con poros en los que se pueda acumular la suciedad o desarrollar microorganismos que contaminen los alimentos o que generen malos olores.",
        img:'../images/living/id12', 
        cuotas:"Hasta 6 cuotas sin interés",
        stock: "enabled",
        colors: "disabled",
        cantidad: 0
    },
];


